
/*
 * This stub is generated by cpprpc, DO NOT modify it!
 */

#ifndef CPPRPC_NOTIFYCLIENTSTUB_HPP
#define CPPRPC_NOTIFYCLIENTSTUB_HPP

#include <cppjson/Value.hpp>

#include <cpprpc/utils.hpp>
#include <cpprpc/client/BaseClient.hpp>
#include <cppweb/Logger.hpp>
#include <cppweb/Singleton.hpp>

namespace CPPRPC {

static auto& logger = CPPWEB::Singleton<CPPWEB::Logger>::GetInstance();

class notifyClientStub: public CPPWEB::nocopyable{
public:
    notifyClientStub(CPPWEB::EventLoop* loop, const CPPWEB::InetAddress& serverAddress):
            m_client(loop, serverAddress)
    {
        m_client.setConnectionCallback([this](const CPPWEB::TCPConnectionPtr& conn){
            if (conn->isConnected()) {
                INFO(logger, "connected");
                m_conn = conn;
                m_cb(m_conn);
            } else {
                INFO(logger, "disconnected");
                assert(m_conn != nullptr);
                m_cb(m_conn);
            }
        });
    }

    void start() { m_client.start(); }

    void setConnectionCallback(const CPPWEB::ConnectionCallback& cb) {
        m_cb = cb;
    }

    
    
void hello(std::string xingming)
{
    cppjson::Value params(cppjson::TYPE_OBJECT);
    
params.addMember(cppjson::Value("xingming"), cppjson::Value(xingming));


    cppjson::Value notify(cppjson::TYPE_OBJECT);
    notify.addMember(cppjson::Value("jsonrpc"), cppjson::Value("2.0"));
    notify.addMember(cppjson::Value("method"), cppjson::Value("notify.hello"));
    notify.addMember(cppjson::Value("params"), cppjson::Value(params));
    assert(m_conn != nullptr);
    m_client.sendNotify(m_conn, notify);
}

void goodbye(std::string xingming)
{
    cppjson::Value params(cppjson::TYPE_OBJECT);
    
params.addMember(cppjson::Value("xingming"), cppjson::Value(xingming));


    cppjson::Value notify(cppjson::TYPE_OBJECT);
    notify.addMember(cppjson::Value("jsonrpc"), cppjson::Value("2.0"));
    notify.addMember(cppjson::Value("method"), cppjson::Value("notify.goodbye"));
    notify.addMember(cppjson::Value("params"), cppjson::Value(params));
    assert(m_conn != nullptr);
    m_client.sendNotify(m_conn, notify);
}


private:
    CPPWEB::TCPConnectionPtr m_conn;
    CPPWEB::ConnectionCallback m_cb;
    BaseClient m_client;
};

}
#endif //CPPRPC_NOTIFYCLIENTSTUB_HPP
